### PR TITLE
Subd bug fix

### LINKED ISSUE #79: An issue with solver interface for Maxwell problem
For distributed meshes with hanging nodes, solving the Maxwell Galerkin problem fails with some mesh partitionings -- likely when the hanging node is on the subdomain interface. This can be replicated by
passing partition:
uniform h-ref (20), single elem href (26) --> (121), distribute mesh (30), solve (40,45)
failing partition:
uniform h-ref (20), distribute mesh (30), single elem href (26) --> (121), solve (40,45)

`par_mumps_sc` solver interface:
```
par_mumps_sc: STARTED

 STEP 1 started : Get assembly info
 STEP 1 finished:      0.00265  seconds

[   0] Number of dof  : nrdof_con =          208
[   0]                  nrdof_tot =          208
[   0] Total non-zeros: nnz       =         8298
[   0] Local non-zeros: nnz_loc   =         4204

 STEP 2 started : Global Assembly
[   1] Local non-zeros: nnz_loc   =         4094
At line 394 of file src/solver/par_mumps/par_mumps_sc.F90
Fortran runtime error: Index '0' of dimension 1 of array 'mumps_par%rhs' below lower bound of 1

Error termination. Backtrace:
```

`PETSc` solver interface:
```
STEP 1 started : Get assembly info
[RANK], sum(petsc_dnz) = [   1],       818
[RANK], sum(petsc_onz) = [   1],       540
 nod_subd .le. 0 !!!
```

### PR DESCRIPTION
**Pull request by stefanhenneking**
Closes #79

### CODE REVIEW

File: trunk/src/adapt/global_href.F90 [hunk 1]
```diff
@@ -18,14 +18,21 @@ subroutine global_href
...
+!       calling refine fixes the issue but is much more expensive
+!       if breaking elements in the right order, it should be safe to do
+!
 !..break the elements
    do i=1,nr_elem
       mdle = ELEM_ORDER(i)
       if (is_leaf(mdle)) then
          call get_isoref(mdle, kref)
          call break(mdle,kref)
+!         call refine(mdle,kref)
```
Comment (jbadger95) [inline trunk/src/adapt/global_href.F90:32]: Why not just make this change at this point? Refine is only about 2x more expensive than break (it typically has 1 extra call to elem_nodes) and with the node_type change it really shouldn't be that much of a bottleneck

File: trunk/src/adapt/global_href.F90 [hunk 2]
```diff
@@ -18,14 +18,21 @@ subroutine global_href
...
       endif
    enddo
+!   call close_mesh
```
Comment (jbadger95) [inline trunk/src/adapt/global_href.F90:35]: I see this is commented out but we shouldn't have to call close mesh; if we start with a 1-irregular mesh before the global h-refinement we should finish with a global h-refinement.

File: trunk/src/meshmod/refresh.F90 [hunk 3]
```diff
@@ -108,5 +107,92 @@ subroutine refresh
...
+         call set_subd(nod,-1)
+      endif
+   enddo
+!$OMP END DO
+!
+!..2. Set subdomains for all (unconstrained) nodes within subdomain
+!$OMP DO
+   do iel=1,NRELES_SUBD
+      mdle = ELEM_SUBD(iel)
+      call set_subd_elem(mdle)
```
Comment (jbadger95) [inline trunk/src/meshmod/refresh.F90:169]: I'm not sure I love this; I like that it only calls `elem_nodes` on the subdomain (so is scalable) but it does add another call to `elem_nodes` to this routine. With the type changes it should be faster but this routine is called up to 6-7 times per grid level on large adaptive problems. This routine (and close_mesh) was a major bottleneck for large adaptive problems. 

Here's my version of Step 1 (I have similar changes for close_mesh). It relies on my bitvisit module (that's where call visit() and reduce_visit() come from); I'll work on committing that once I have my code working with the node type changes. Since we already mark all the nodes connected to a rank's subdomain in step 1 we could simply loop over NODES and check if there are any active nodes (with subd set?) that have not been visited.

It's probably fine for now; I can work on integrating these changes along with the other ones.

```suggestion 
!
!--------------------------------------------------------------------
! Step 1 : raise visitation flag for vertex, edge and face nodes of |
!          all active elements                                      |
!--------------------------------------------------------------------
!$omp parallel default(shared)
!$omp do private(iel,mdle,subd,type,i,nodesl,norientl) schedule(guided)
   do iel=1,NRELES_SUBD
!
      mdle = ELEM_SUBD(iel)
!
      call elem_nodes(mdle, nodesl,norientl)
!
      ntype=NODES(mdle)%ntype
      nvef = nvert(ntype)+nedge(ntype)+nface(ntype)
!
      do i=1,nvef
!     ...bitflag stores visit in bit collection (better for MPI)
         call visit(nodesl(i))
!
!     ...if node is visited by an element within my subdomain,
!        add node to my subdomain (need its dofs). this flag will
!        indicate that dofs must be allocated in activation.
         if (DISTRIBUTED) then
            call set_subd(nodesl(i),subd)
         endif
      enddo
!
   enddo
!$omp end do
!$omp end parallel
!
!..Reduce over node flag
   if (DISTRIBUTED) then
      call reduce_visit
   endif
```

**Review by jbadger95 — APPROVED** [review]
Nice find, that was tricky!

File: trunk/src/adapt/global_href.F90 (hunk 1 above)
Comment (stefanhenneking) [reply trunk/src/adapt/global_href.F90:32]: Yes, I can make that change here, so it doesn't cause trouble in the future.

File: trunk/src/adapt/global_href.F90 (hunk 2 above)
Comment (stefanhenneking) [reply trunk/src/adapt/global_href.F90:35]: You're right, `close_mesh` should not be needed here. I had tested first with putting the removal of active constrained nodes outside the subdomain into the `close_mesh` function which would be potentially cheaper than having it in `refresh` since `close_mesh` may call `refresh` multiple times. However, having it in `refresh` is the safer option if we want to enable refinements that don't call `close_mesh` at all such as the `global_href`.

File: trunk/src/meshmod/refresh.F90 (hunk 3 above)
Comment (stefanhenneking) [reply trunk/src/meshmod/refresh.F90:169]: We can definitely optimize the visitation of nodes as needed if your bitvisit module is faster. The suggested change here would need to be adapted though--it's missing constrained nodes.

Comment (jbadger95) [reply trunk/src/meshmod/refresh.F90:169]: I see; this is probably fine then, to get constrained nodes we'll need another call anyway.

Bitvisit just marks visitation in an array that can be quickly and conveniently MPI_reduced. When I bit encode the visitation flags I have to put atomic directives and it turns out that can be fairly slow with a lot of threads so for now I'm actually not bitencoding, just marking with integers and reducing.

**Comment by stefanhenneking** [comment]
@jbadger95 @ac1512 Merging this now into `master` but not into `next`. Once `next` is confirmed stable, we can merge it back into `master` resolving merge conflicts if there are any.
